#!/bin/bash
# This script is executed after the package is installed

set -e

#############################
## BEGIN ocn Neuron config 
#############################
# Define the username & home folder
USERNAME="odns-api-client"
SERVICE_NAME="odns-api-client"
HOME_FOLDER="/opt/ocn/odns-api-client"
LOG_FOLDER="/var/log/odns-api-client"

# Check if the home folder exists and change the owner
if [ -d "$HOME_FOLDER" ]; then
    echo "Changing ownership of $HOME_FOLDER to $USERNAME..."
    chown -R "$USERNAME":"$USERNAME" "$HOME_FOLDER"
else
    echo "Home folder $HOME_FOLDER does not exist."
fi

# Check if the log folder exists, create and change the owner
if [ -d "$LOG_FOLDER" ]; then
    echo "Changing ownership of $LOG_FOLDER to $USERNAME..."
    chown -R "$USERNAME":"$USERNAME" "$LOG_FOLDER"
else
    mkdir -p "$LOG_FOLDER"
    chown -R "$USERNAME":"$USERNAME" "$LOG_FOLDER"
fi

# Enable and start service 
# echo "Start $SERVICE_NAME..."
# systemctl start "$SERVICE_NAME"

# Right permision
echo "Right permision sudoers"
chown root:root /etc/sudoers.d/odns-api-client
chmod 400 /etc/sudoers.d/odns-api-client

# Enable service
echo "Enable $SERVICE_NAME..."
systemctl enable "$SERVICE_NAME"
#############################
## END ocn Neuron config 
#############################

exit 0
