package handler

import (
	"net/http"
	"time"

	"github.com/quanNaNbk03/monitor-demo/pkg/api/health"

	apimodels "github.com/quanNaNbk03/monitor-demo/pkg/api/health"

	"github.com/gin-gonic/gin"
)

// HealthHandler implements the health.ServerInterface generated by oapi-codegen
type HealthHandler struct{}

// NewHealthHandler creates a new health handler
func NewHealthHandler() *HealthHandler {
	return &HealthHandler{}
}

// Ensure HealthHandler implements health.ServerInterface
var _ health.ServerInterface = (*HealthHandler)(nil)

// GetHealth implements the health check endpoint
// (GET /ping)
func (h *HealthHandler) GetHealth(c *gin.Context) {
	now := time.Now()
	response := apimodels.HealthResponse{
		Status:    "ok",
		Timestamp: now,
	}
	c.JSON(http.StatusOK, response)
}
