package handler

import (
	"net/http"

	"github.com/quanNaNbk03/monitor-demo/internal/server/service"
	"github.com/quanNaNbk03/monitor-demo/pkg/api/vm"

	"github.com/gin-gonic/gin"

	"git.ocn.com.vn/ocn/common/httpbase"
)

// VMHandler implements the vm.ServerInterface generated by oapi-codegen
type VMHandler struct {
	monitorVMService       service.MonitorVMService
	victoriaMetricsService service.VictoriaMetricsService
}

// NewVMHandler creates a new vm handler
func NewVMHandler(monitorVMService service.MonitorVMService, victoriaMetricsService service.VictoriaMetricsService) *VMHandler {
	return &VMHandler{
		monitorVMService:       monitorVMService,
		victoriaMetricsService: victoriaMetricsService,
	}
}

// Ensure VMHandler implements vm.ServerInterface
var _ vm.ServerInterface = (*VMHandler)(nil)

func (h *VMHandler) GetMonitorVMWithProm(c *gin.Context, id uint64, metricType vm.VMMetricType, params vm.GetMonitorVMWithPromParams) {
	res, ierr := h.monitorVMService.GetMonitorVMByType(c.Request.Context(), id, metricType, params)
	if ierr != nil {
		httpbase.ReturnErrorResponse(c, ierr)
		return
	}
	httpbase.ReturnSuccessResponse(c, http.StatusOK, res)
}

func (h *VMHandler) GetMonitorVMWithVM(c *gin.Context, id uint64, metricType vm.VMMetricType, params vm.GetMonitorVMWithVMParams) {
	res, ierr := h.victoriaMetricsService.GetMonitorVMByType(c.Request.Context(), id, metricType, params)
	if ierr != nil {
		httpbase.ReturnErrorResponse(c, ierr)
		return
	}
	httpbase.ReturnSuccessResponse(c, http.StatusOK, res)
}
