package handler

import (
	"net/http"

	"github.com/gin-gonic/gin"
	zone "github.com/quanNaNbk03/monitor-demo/pkg/api/zoneclient"

	"github.com/quanNaNbk03/monitor-demo/internal/server/dto"
	"github.com/quanNaNbk03/monitor-demo/internal/server/service"

	"git.ocn.com.vn/ocn/common/httpbase"
)

// ZoneClientHandler implements the health.ServerInterface generated by oapi-codegen
type ZoneClientHandler struct {
	zoneService service.ZoneService
}

// NewZoneClientHandler creates a new health handler
func NewZoneClientHandler(zoneService service.ZoneService) *ZoneClientHandler {
	return &ZoneClientHandler{
		zoneService: zoneService,
	}
}

// Ensure ZoneHandler implements zone.ServerInterface
var _ zone.ServerInterface = (*ZoneClientHandler)(nil)

func (h *ZoneClientHandler) Get(c *gin.Context, id uint64) {
	res, err := h.zoneService.Get(c.Request.Context(), id)
	if err != nil {
		httpbase.ReturnErrorResponse(c, err)
		return
	}

	httpbase.ReturnSuccessResponse(c, http.StatusOK, res)
}

func (h *ZoneClientHandler) Update(c *gin.Context, id uint64) {
	req := new(zone.UpdateZoneClientRequest)
	if err := httpbase.BindInput(c, req); err != nil {
		httpbase.ReturnErrorResponse(c, err)
		return
	}

	if err := h.zoneService.Update(c.Request.Context(), id, &dto.UpdateZoneRequest{DnsSec: req.Dnssec}); err != nil {
		httpbase.ReturnErrorResponse(c, err)
		return
	}
	httpbase.ReturnSuccessResponse(c, http.StatusOK, nil)
}

func (h *ZoneClientHandler) List(c *gin.Context) {
	in := new(dto.ListZonesJSONBody)
	if err := httpbase.BindInput(c, in); err != nil {
		httpbase.ReturnErrorResponse(c, err)
		return
	}
	res, err := h.zoneService.List(c.Request.Context(), in)
	if err != nil {
		httpbase.ReturnErrorResponse(c, err)
		return
	}
	httpbase.ReturnSuccessResponse(c, http.StatusOK, res)
}
